CREATE TABLE IF NOT EXISTS catalog_state (
    state_key TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    last_sync_at TIMESTAMPTZ,
    note TEXT NOT NULL DEFAULT '',
    satellite_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satellites (
    id TEXT PRIMARY KEY,
    norad_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    country TEXT NOT NULL DEFAULT '',
    owner_code TEXT NOT NULL DEFAULT '',
    owner_name TEXT NOT NULL DEFAULT '',
    orbit_type TEXT NOT NULL DEFAULT '',
    purpose TEXT NOT NULL DEFAULT '',
    latitude DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude DOUBLE PRECISION NOT NULL DEFAULT 0,
    altitude DOUBLE PRECISION NOT NULL DEFAULT 0,
    velocity DOUBLE PRECISION NOT NULL DEFAULT 0,
    period DOUBLE PRECISION NOT NULL DEFAULT 0,
    inclination DOUBLE PRECISION NOT NULL DEFAULT 0,
    epoch TEXT NOT NULL DEFAULT '',
    tle_name TEXT NOT NULL,
    tle_line1 TEXT NOT NULL,
    tle_line2 TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'unknown',
    position_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_satellites_country ON satellites (country);
CREATE INDEX IF NOT EXISTS idx_satellites_purpose ON satellites (purpose);
CREATE INDEX IF NOT EXISTS idx_satellites_orbit_type ON satellites (orbit_type);
CREATE INDEX IF NOT EXISTS idx_satellites_name ON satellites (name);
CREATE INDEX IF NOT EXISTS idx_satellites_position_updated_at ON satellites (position_updated_at);

CREATE TABLE IF NOT EXISTS catalog_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    mode TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    imported_count INTEGER NOT NULL,
    total_satellites INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
